# Generated by Django 5.0.1 on 2024-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='превью')),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name='дата создания')),
                ('sign_publication', models.CharField(max_length=150, verbose_name='признак публикации')),
                ('number_views', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
