# Generated by Django 5.0.1 on 2024-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='положительно опубликованы'),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
