# Generated by Django 5.0.1 on 2024-02-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_published_article_views_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='number_views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
