# Generated by Django 5.0.1 on 2024-02-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_article_number_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
