# Generated by Django 5.0.1 on 2024-02-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
